# Copyright (C) 2017, 2018 Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

language: python
dist: trusty
sudo: required

python:
- '3.5'

before_install:
- pip install -U pip
- pip install -U setuptools
- pip install -r requirements.txt
- peru sync

script:
- make html
- make publish

after_success:
- cp README.md output/
- mv *.png output/
- sed -i "s#https://github.com#https://${GHTOKEN}@github.com#g" .git/config
- sed -i "s#git@github.com:#https://${GHTOKEN}@github.com/#g" .git/config
- make github
