# Copyright (C) 2017, 2018 Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

language: python
sudo: required

before_install:
- sudo apt-get -y install pandoc
- pip install -U pip
- pip install -U setuptools
- pip install -r requirements.txt
- find ${HOME} -name git_plugin.py -exec chmod -v +x {} \;
- peru sync

script:
- make html
- make publish

after_success:
- touch output/.nojekyll
- cp README.md output/
- mv *.png output/
- sed -i "s#https://github.com#https://${GHTOKEN}@github.com#g" .git/config
- sed -i "s#git@github.com:#https://${GHTOKEN}@github.com/#g" .git/config
- make github
