name = "reveal-hugo"
license = "MIT"
licenselink = "https://github.com/joshed-io/reveal-hugo/blob/master/LICENSE"
homepage = "https://reveal-hugo.dzello.com/"
tags = ["presentation", "revealjs"]
features = ["presentation"]

[author]
name = "Josh Dzielak"
homepage = "https://joshed.io/"

[original]
name = "reveal.js"
homepage = "https://revealjs.com"
repo = "https://github.com/hakimel/reveal.js/"

[module]
    [module.hugoVersion]
        min = "0.93.0"
