---
name: hugo

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Hugo
        uses: crazy-max/ghaction-hugo@v3.0.0
        with:
          version: latest
          extended: true
          args: --minify --verbose
      - name: Deploy to GitHub Pages
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: gh-pages
          build_dir: public
          jekyll: false

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
